# **Machine Learning**

In [18]:
#importing the libraries
import numpy as np
import pandas as pd

#### **Load the data**

In [19]:
df_pre=pd.read_csv("Absenteeism_preprocessed.csv")
df_pre.head()

reason_grp1  reason_grp2  reason_grp3  reason_grp4  Transportation Expense  \
0        False        False        False         True                     289   
1        False        False        False        False                     118   
2        False        False        False         True                     179   
3         True        False        False        False                     279   
4        False        False        False         True                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  month  Day of the week  
0         2     1                          4      7                1  
1         1     0                          0      7                1  
2         0     0                          2      7                2  
3         2     0                          4      7                3  
4         2     1                          2      7                3

#### **Creating the targets**

In [20]:
df_pre['Absenteeism Time in Hours'].median()

3.0

If Absenteeism Time in Hours<=3 then moderately absent => 0

If Absenteeism Time in Hours>=3 then excessively absent => 1

In [21]:
targets=np.where(df_pre['Absenteeism Time in Hours']>df_pre['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [22]:
df_pre['Excessive Absenteeism']=targets
df_pre.head()

reason_grp1  reason_grp2  reason_grp3  reason_grp4  Transportation Expense  \
0        False        False        False         True                     289   
1        False        False        False        False                     118   
2        False        False        False         True                     179   
3         True        False        False        False                     279   
4        False        False        False         True                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  month  Day of the week  \
0         2     1                          4      7                1   
1         1     0                          0      7                1   
2         0     0                          2      7                2   
3         2     0                          4      7                3   
4         2     1                          2      7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

#### **Comments on targets**

In [23]:
targets.sum()/targets.shape[0]

0.45571428571428574

Usually 60-40 split will work equally well for logistic regression
But here we have 45-55 split

In [24]:
#dropping absenteeism in hours
df_pre.drop('Absenteeism Time in Hours',axis=1,inplace=True)
df_pre.head()

reason_grp1  reason_grp2  reason_grp3  reason_grp4  Transportation Expense  \
0        False        False        False         True                     289   
1        False        False        False        False                     118   
2        False        False        False         True                     179   
3         True        False        False        False                     279   
4        False        False        False         True                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  month  Day of the week  Excessive Absenteeism  
0         2     1      7                1                      1  
1         1     0      7                1                      0  
2         0     0      7                2                      0  
3         2     0      7                3                      1  
4         2     1      7                3                      0

In [25]:
df_target=df_pre.copy()

In [26]:
unscaled_ip=df_target.iloc[:,:-1]

#### **Standardize data**

In [27]:
from sklearn.preprocessing import StandardScaler
#datapt-mean/sd of each point
absenteeismscaler=StandardScaler()
absenteeismscaler.fit(unscaled_ip)

StandardScaler()

In [28]:
scaled_ip=absenteeismscaler.transform(unscaled_ip)

In [29]:
scaled_ip

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.00772546],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
        -0.3882935 ,  0.66825259]])

In [30]:
scaled_ip.shape

(700, 14)

#### **Splitting the data to train and shuffle**

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
train_test_split(scaled_ip,targets)

[array([[ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.3882935 , -0.00772546],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
          0.18272635,  0.66825259],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.10278357, -0.68370352],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          0.46823627,  0.66825259],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.95931334, -0.68370352],
        [-0.57735027, -0.09298136, -0.31448545, ...,  1.12666297,
          1.61027597, -1.35968157]]),
 array([[ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
         -1.24482327, -0.68370352],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
          1.32476605, -1.35968157],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
         -1.53033319, -1.35968157],
        ...,
        [-0.57735027, -0.09298136,  3.17979734, ..., -

80% training 20% testing

In [33]:
xtrain,xtest,ytrain,ytest=train_test_split(scaled_ip,targets,train_size=0.8,shuffle=True,random_state=20)
print(xtrain.shape,xtest.shape,ytrain.shape,ytest.shape)

(560, 14) (140, 14) (560,) (140,)


#### **Logistic Regression Model with sklearn**

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [35]:
reg=LogisticRegression()

In [36]:
reg.fit(xtrain,ytrain)

LogisticRegression()

In [37]:
#accuracy 78%
reg.score(xtrain,ytrain)

0.7821428571428571

#### Manually check the accuracy

In [38]:
model_op=reg.predict(xtrain)
model_op

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [39]:
model_op==ytrain

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [40]:
np.sum(model_op==ytrain)/model_op.shape[0]

0.7821428571428571

Finding the intercept and coefficient

In [41]:
reg.intercept_

array([-0.20545161])

In [42]:
reg.coef_

array([[ 1.93104665,  0.30656877,  1.41635514,  1.15214043,  0.69807752,
        -0.04101852, -0.20073597, -0.0038131 ,  0.3183322 , -0.15049738,
         0.37732406, -0.31799345,  0.17922939, -0.0705115 ]])

In [43]:
unscaled_ip.columns.values

array(['reason_grp1', 'reason_grp2', 'reason_grp3', 'reason_grp4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'month', 'Day of the week'], dtype=object)

In [44]:
feature_names=unscaled_ip.columns.values

In [45]:
summary_table=pd.DataFrame (columns=['Feature name'], data = feature_names)

summary_table['Coefficient']=np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0               reason_grp1     1.931047
1               reason_grp2     0.306569
2               reason_grp3     1.416355
3               reason_grp4     1.152140
4    Transportation Expense     0.698078
5          Distance to Work    -0.041019
6                       Age    -0.200736
7   Daily Work Load Average    -0.003813
8           Body Mass Index     0.318332
9                 Education    -0.150497
10                 Children     0.377324
11                     Pets    -0.317993
12                    month     0.179229
13          Day of the week    -0.070512

In [46]:
summary_table.index=summary_table.index+1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

Feature name  Coefficient
1               reason_grp1     1.931047
2               reason_grp2     0.306569
3               reason_grp3     1.416355
4               reason_grp4     1.152140
5    Transportation Expense     0.698078
6          Distance to Work    -0.041019
7                       Age    -0.200736
8   Daily Work Load Average    -0.003813
9           Body Mass Index     0.318332
10                Education    -0.150497
11                 Children     0.377324
12                     Pets    -0.317993
13                    month     0.179229
14          Day of the week    -0.070512
0                 Intercept    -0.205452

#### **Interpretting the coefficients**

In [47]:
#they are also called as weights
#the weight wwhich is bigger, the more important the feature is
#in logistic regression, 
#log(odds)=intercept+b1x1+b2x2+...+bnxn

#exponential of coefficients
summary_table['Odds_ratio']=np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_ratio
1               reason_grp1     1.931047    6.896725
2               reason_grp2     0.306569    1.358755
3               reason_grp3     1.416355    4.122069
4               reason_grp4     1.152140    3.164960
5    Transportation Expense     0.698078    2.009885
6          Distance to Work    -0.041019    0.959811
7                       Age    -0.200736    0.818128
8   Daily Work Load Average    -0.003813    0.996194
9           Body Mass Index     0.318332    1.374833
10                Education    -0.150497    0.860280
11                 Children     0.377324    1.458377
12                     Pets    -0.317993    0.727608
13                    month     0.179229    1.196295
14          Day of the week    -0.070512    0.931917
0                 Intercept    -0.205452    0.814279

In [48]:
#sort_values
summary_table.sort_values('Odds_ratio', ascending=False)
#most important to least important

Feature name  Coefficient  Odds_ratio
1               reason_grp1     1.931047    6.896725
3               reason_grp3     1.416355    4.122069
4               reason_grp4     1.152140    3.164960
5    Transportation Expense     0.698078    2.009885
11                 Children     0.377324    1.458377
9           Body Mass Index     0.318332    1.374833
2               reason_grp2     0.306569    1.358755
13                    month     0.179229    1.196295
8   Daily Work Load Average    -0.003813    0.996194
6          Distance to Work    -0.041019    0.959811
14          Day of the week    -0.070512    0.931917
10                Education    -0.150497    0.860280
7                       Age    -0.200736    0.818128
0                 Intercept    -0.205452    0.814279
12                     Pets    -0.317993    0.727608

A feature is not important if its coefficient is around 0 and if its odd ratio is around 1

- the features like Daily Work Load Average, Distance to Work, Day of the week can be dropped

In [49]:
#Backward Elimination
#dropping the features

#### **Testing the model**


In [50]:
reg.score(xtest,ytest)

0.7357142857142858

In [52]:
predicted_prob=reg.predict_proba(xtest)
predicted_prob

array([[0.74257955, 0.25742045],
       [0.5925467 , 0.4074533 ],
       [0.37477205, 0.62522795],
       [0.81220118, 0.18779882],
       [0.06242351, 0.93757649],
       [0.30401231, 0.69598769],
       [0.2898588 , 0.7101412 ],
       [0.09381436, 0.90618564],
       [0.80041389, 0.19958611],
       [0.76242418, 0.23757582],
       [0.46015423, 0.53984577],
       [0.15958302, 0.84041698],
       [0.05486339, 0.94513661],
       [0.73691836, 0.26308164],
       [0.26041573, 0.73958427],
       [0.56581205, 0.43418795],
       [0.52364792, 0.47635208],
       [0.54961752, 0.45038248],
       [0.37711258, 0.62288742],
       [0.03029273, 0.96970727],
       [0.69620413, 0.30379587],
       [0.80482254, 0.19517746],
       [0.37526671, 0.62473329],
       [0.39786729, 0.60213271],
       [0.20389266, 0.79610734],
       [0.757606  , 0.242394  ],
       [0.47711679, 0.52288321],
       [0.89489195, 0.10510805],
       [0.01741733, 0.98258267],
       [0.79722636, 0.20277364],
       [0.

In [53]:
predicted_prob.shape

(140, 2)

In [54]:
predicted_prob[:,1]

array([0.25742045, 0.4074533 , 0.62522795, 0.18779882, 0.93757649,
       0.69598769, 0.7101412 , 0.90618564, 0.19958611, 0.23757582,
       0.53984577, 0.84041698, 0.94513661, 0.26308164, 0.73958427,
       0.43418795, 0.47635208, 0.45038248, 0.62288742, 0.96970727,
       0.30379587, 0.19517746, 0.62473329, 0.60213271, 0.79610734,
       0.242394  , 0.52288321, 0.10510805, 0.98258267, 0.20277364,
       0.38261365, 0.71248173, 0.70433017, 0.56498545, 0.19517746,
       0.54136914, 0.20858374, 0.79748176, 0.44333025, 0.60269711,
       0.20934119, 0.39978119, 0.21674533, 0.130493  , 0.84380242,
       0.63321017, 0.71989918, 0.26593191, 0.20068168, 0.17144387,
       0.56340328, 0.10665044, 0.68331698, 0.28218033, 0.87249104,
       0.47987794, 0.92383947, 0.24640568, 0.10986834, 0.11048515,
       0.72160806, 0.67379904, 0.30850902, 0.84105813, 0.18727994,
       0.25657327, 0.01841822, 0.22412107, 0.78665127, 0.30473196,
       0.20798101, 0.09624361, 0.93225205, 0.45894615, 0.65042